#!/bin/bash
# grep and edit
JS_EXCLUDE='--exclude-dir build --exclude-dir node_modules'
COLOR='--color=always'
while [ -n "$1" ]; do
    [ "$1" = '-x' ] && { shift ; X="$X --exclude-dir $1 " ; shift ; continue ; }
    [ "$1" = '-cpp' ] && { shift ; I="$I `echo --include=\*.{cpp,h,c,hpp,inl}`" ; continue ; }
    [ "$1" = '-txt' ] && { shift ; I="$I --include=*.txt" ; continue ; }
    [ "$1" = '-js' ] && { shift ; I="$I `echo --include=\*.{js,jsx}`" X="$X $JS_EXCLUDE" ; continue ; }
    [ "$1" = '-json' ] && { shift ; I="$I `echo --include=\*.{json}`" X="$X $JS_EXCLUDE" ; continue ; }
    [ "$1" = '-css' ] && { shift ; I="$I `echo --include=\*.{css}`" ; continue ; }
    [ "$1" = '--ni' ] && { NONINTERACTIVE=1; shift ; continue ; }
    [ "$1" = '--nc' ] && { COLOR='' ; shift ; continue ; }
    [ "$1" = '--verbose' ] && { VERBOSE=1 ; shift ; continue ; }
    [ -n "$EXPR" ] && EXPR="$EXPR $1" || EXPR="$1"
    shift
done

# Unnamed pipe has limited size, so have to use tmp file instead
BUF_FILE=/tmp/$$
function cleanup {
    rm -f $BUF_FILE &
    exit
}
trap cleanup EXIT SIGINT

exec 4>&1
exec 5>$BUF_FILE
[ -n "$VERBOSE" ] && echo "grep $COLOR --exclude-dir \.svn --exclude-dir \.git $X $I -Inr \"$EXPR\""
[ -n "$NONINTERACTIVE" ] && { grep $COLOR --exclude-dir \.svn --exclude-dir \.git $X $I -Inr "$EXPR" . ;\
    exit ; }
LIST="`grep $COLOR --exclude-dir \.svn --exclude-dir \.git $X $I -Inr "$EXPR" .|\
    tee >(cat|sed '='|sed 'N;s/\n/:/'|tee >((cat|sed 's/$/\n/') 1>&5) 1>&4)|\
    (sed -e 's,\x1B\[[0-9;]*[a-zA-Z],,g' -e 's,:.*,,'|sort -u)`" 
COUNT=$(echo $LIST|wc -w)
echo "$COUNT files found"
(( $COUNT )) || exit
read I
[ -z "$I" ] && { vim $LIST -O$(($COUNT<3?$COUNT:3)) +/"$EXPR" ; exit ; }
while read line ; do
    [ $I = "`echo $line|sed 's/:.*//'`" ] &&\
        STRIPPED=`echo $line|sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"` &&\
        LINE_NUM="`echo $STRIPPED|sed 's/^[^:]*:[^:]*://;s/:.*//'`" &&\
        EF=`echo $STRIPPED|sed -e 's/^[^:]*://;s/:.*//'` &&\
        break
done <$BUF_FILE
[ -n "$EF" ] && [ -n "$LINE_NUM" ] && vim $EF +/"$EXPR" -c $LINE_NUM && exit
echo "no entry #'$I'"
